In the following environment
ArchLinux 4.4.5-1
Java openjdk version "1.8.0_74" 64-Bit Server VM (build 25.74-b02, mixed mode)

we have got the following error while code compilation 

test(net.sf.hajdbc.sql.BlobTest)  Time elapsed: 0.283 sec  <<< ERROR!
java.sql.SQLException: lob is no longer valid
	at net.sf.hajdbc.sql.BlobTest.test(BlobTest.java:72)
Caused by: org.hsqldb.HsqlException: lob is no longer valid
	at net.sf.hajdbc.sql.BlobTest.test(BlobTest.java:72)

HSQLDB version upgrade to 2.3.4 should solve the problem